sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/google-cloud-sdk
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - SHA=$(git rev-parse HEAD)
before_install:
  - openssl aes-256-cbc -K $encrypted_248412cf5212_key -iv $encrypted_248412cf5212_iv -in service-account.json.enc -out service-account.json -d
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud version
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project k2multi-212923
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials k2cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker pull stephengrider/react-test:latest
  # - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client
  # - docker push stephengrider/react-test:latest

script:
  - echo tests pass
  # - docker run stephengrider/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
